### PR TITLE
feat: Widescreen support

### LINKED ISSUE #501: Wide Screen Support
Support the wider screen can improve the user experience at PC or Tablet devices.

### PR DESCRIPTION
**Pull request by hv0905**
close #501

### CODE REVIEW

**Review by xxyzz — APPROVED** [review]

**Comment by Anduin2017** [comment]
Hi, thanks for this contribution! That was really cool! 👍 👍 👍

Probably the best PR in 2019🎉!

Before we merging this, let's carefully test it and try to fix as many bugs as we can.

Thank you really so much! You are the best developer I've ever seen!  💯

**Comment by Anduin2017** [comment]
Annotation 2019-06-20 224823

I guess the shadow here shall be removed.

**Comment by Anduin2017** [comment]
What about adding a light shadow on the right part like this?

59567642-b2c70580-90a2-11e9-9471-ead7aa831b60

**Comment by Anduin2017** [comment]
I suggest changing this larger so that on electron, the wide screen mode is the default.

https://github.com/AiursoftWeb/Kahla.App/blob/a1929f668d597d98c9fd44b2c22b40c29c357a23/src/index.js#L22

**Comment by Anduin2017** [comment]
Annotation 2019-06-20 225235

It seems that the shadow shall not go out of its component. I suggest fixing this shadow issue.

You can try this tool if you like:

https://www.cssmatic.com/box-shadow

**Comment by Anduin2017** [comment]
Annotation 2019-06-20 225453

I suggest that replacing this icon to a left arrow if it means `goes back` not close the right part. But the current is already so good now! Really nice!

**Comment by Anduin2017** [comment]
Annotation 2019-06-20 225653

I have no idea about this background color change. Maybe it was a mistake or a bug.

**Comment by Anduin2017** [comment]
I suggest using color `$primary-color-depth3` here so that it will be more readable:

Annotation 2019-06-20 225931

**Comment by Anduin2017** [comment]
A strange shadow.

Annotation 2019-06-21 000019


It seems that it was caused by a wrong height of some element.

**Comment by Anduin2017** [comment]
Annotation 2019-06-21 002629

I guess this component shall not have a `go back` button.

**Comment by Anduin2017** [comment]
The yellow bar issue.

**Comment by hv0905** [comment]
Everything clear! Check it out again pls. @Anduin2017

**Review by Anduin2017 — APPROVED** [review]

**Pull request merged**
