### PR TITLE
feat: add a sound alert for the new message

### LINKED ISSUE #579: Sound alert on new messages.
## What do you suggest us to do?

Now that on new notifications, if you are focusing the talking page but doing some stuff on other windows, like playing a game, you won't get any notifications.

If you can play a simple sound like below when on new notifications, (Even when the user is focusing) It will make it less possible to miss new messages.

## Additional context

Sound file:

https://oss.aiursoft.com/ColossusPublic/a2e874964d154405b00978abea67f6c2.mp3?name=a.mp3

### PR DESCRIPTION
**Pull request by hv0905**
close #579

### CODE REVIEW

**Review by Anduin2017 — APPROVED** [review]

**Comment by Anduin2017** [comment]
Nice fix!

**Comment by xxyzz** [comment]
Don't forget to upgrade the service worker cache version.

**Review by xxyzz — COMMENTED** [review]
Don't forget to upgrade the service worker cache version.

**Comment by Anduin2017** [comment]
Thanks for the advice! @xxyzz  So how is our service worker upgraded? Is there any document which we can follow?

**Pull request merged**
