### PR TITLE
feat: support connecting to community server

### LINKED ISSUE #785: Kahla 4.0.0 - Multiple region and private server support
Kahla plans to introduce server switching in 4.0.0.

# Why we do this

This is for users in many different regions, and these users do not need to download an additional Kahla app. For these users, multiple regions are imperceptible. The domain names they visit are web.kahla.app, and they download the same Kahla App and Kahla CLI.
For example, if we deploy a Kahla server in Shanghai, China, all users in China will connect to this Kahla server in Shanghai.

For the future, there may be enterprises deploying Kahla App on their internal network. Multi-server Kahla allows data not to leave the corporate network, while users still use the same version of the Kahla app, and can switch between the public Kahla server and their private Kahla server at any time.

Also, this will encourage developers to deploy Kahla servers privately.

# What data can be synchronized across servers?

The user's basic information, including ID, nickname, Bio, avatar, password, and log in log, data is exchanged between servers in different regions.

The user's friends, chat messages, stargate channels, files, theme colors, and privacy settings will not be synchronized.

# Use case

## Servers fetching algorithm

www.kahla.app will provide an API that allows querying the list of all servers currently registered. The return value will include the server address, the server's API level, and the server name.

## Servers speed test algorithm

Kahla App will support server speed measurement use cases. 

Its implementation is:
Make an HTTP request to all servers in the server list at the same time asynchronously, requesting `/`. The difference between the time to start the request and the time to obtain the response is used to obtain the server lag value.

## Servers selection algorithm

Kahla App will support the server automatic selection algorithm. Its implementation is:

* If there is a server address in the local storage, the local server address is used.
* If there is no server address in the local storage, the server speed test is performed. Store the address of the server with the lowest latency in the speed measurement result in local storage.

Generally, a device will only execute the server speed test algorithm once and only once. Saved values will be used later.

# Components to be changed

## Landing page

In Kahla's landing page, the server's automatic selection algorithm will be triggered and the results of the server selection algorithm will be displayed.

image

When the user presses "Region: {Current Server Name} (Click to switch)", the server selection component should be displayed.

## Server selection component

image

In the server selection component, all the servers returned by the server list algorithm will be displayed.

Users can see the server name. Users can view the results returned by the server speed measurement algorithm. If the API level of the server is not consistent with the Kahla App, the user will display a warning when trying to switch, but it does not prevent him from continuing to connect.

There should be one on the list: called `Other Kahla Server`. If the user presses this item, he is asked to enter the address of his own Kahla server.

### PR DESCRIPTION
**Pull request by hv0905**
close #785

### CODE REVIEW

**Comment by Anduin2017** [comment]
OHHH! Superfast feature implementation!

**Comment by Anduin2017** [comment]
This pull request is super nice! But, we are not planning to release this feature in the 3.9.2 version. Please leave this pull request open. We will fix more bugs for the 3.9.1 version before releasing 3.9.2. After 3.9.2 is released, we gonna work on this one!

The next version of Kahla, which also supports the customized server connection, is 4.0.0.

Please ***DO NOT MERGE*** this pull request before release 3.9.2.

**Review by Anduin2017 — CHANGES_REQUESTED** [review]
Pending for the next production release.

**Comment by Anduin2017** [comment]
This pull request is super nice! While this pull request can not be merged currently, there are still some cases which shall be changed:

* The client-side shall not code the official server in code, in case we changed the server name or push key. Always download the server configuration from API.

As for the API, it will return all accessible servers. You need to add two filters.

### Filter 1: Domain filter.

Domain filter works only on the web. Not filter in electron. For web, page cookie is limited in one domain. Filter the `server.domain.client` to your current domain. If the domain is wrong, ignore it.

### Filter 2: API version filter.

API version filter works on all platforms. But the user still can see the servers which are outdated. Only show a warning if the user is trying to connect an outdated server or using an outdated client to connect to a new server.

**Comment by Anduin2017** [comment]
Seems you are still working on it. So, is this pull request ready to be check and merged?

**Comment by hv0905** [comment]
> Seems you are still working on it. So, is this pull request ready to be check and merged?

You can review it now.

**Review by Anduin2017 — APPROVED** [review]

**Pull request merged**
