### PR TITLE
Support beautiful friend request page.

### PR DESCRIPTION
**Pull request by BigSnow1**
I created this branch to add CSS styles to my friendrequests page.
Now you can receive request messages and choose to accept them or decline ithem.

### CODE REVIEW

**Review by Anduin2017 — APPROVED** [review]
Well done. Do solve the problem. I approve to merge it.

**Comment by BigSnow1** [comment]
My first pull request!

**Comment by Anduin2017** [comment]
Well done.

**Comment by BigSnow1** [comment]
ok

**Pull request merged**
