### PR TITLE
fix: display the first error info when server response -10

### PR DESCRIPTION
**Pull request by Xiangrui2019**

### CODE REVIEW

**Review by hv0905 — CHANGES_REQUESTED** [review]
The field `items` isn’t always available, you  should check before reading `items`

**Comment by Xiangrui2019** [comment]
> 该字段`items`并非始终可用，您应在阅读前进行检查`items`

yes

**Comment by Anduin2017** [comment]
The response model may not always be `AiurCollection`. 

Please reference here:

https://github.com/AiursoftWeb/Kahla.App/blob/dev/src/app/Controllers/signin.component.ts#L52

for @xxyzz's best practice.

**Review by hv0905 — CHANGES_REQUESTED** [review]
Check if error code is -10

**Pull request closed without merging**
