### PR TITLE
New upload api

### LINKED ISSUE #679: Refactor upload process
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## About the new API

- Providor: `Kahla and Probe`

## About the API feature

This API produces a new way to upload files.

We used to call `Storage/UploadIcon` and `Storage/UploadFile` to save files to Kahla. This is good. But...

It works slow and hard to maintain. Because all the files will be saved to Kahla server locally. And will be transferred to Probe later. This makes it slow and unstable to upload. And pollute Kahla's code.

So we gonna refactor this process.

-------

First the client shall call the `init upload` API to get a valid public token. The document is here:

[Kahla Upload API](https://wiki.aiursoft.com/ReadDoc/Kahla/Storage.md)

Server will return a valid upload address. Like this:

```json
{
	"value": "https://probe.aiursoft.com/Files/UploadFile/kahla-user-files/conversation-4/2019-09-21?pbtoken=eyJza3D",
	"code": 0,
	"message": "Token is given. You can not upload your file to that address. And your will get your response as 'FilePath'."
}
```

When you get the address and token, you can start uploading the file **directly** to probe. Kahla won't touch that file.

To upload a file to probe, simply call that address using HTTP Post. The document is here:

[Probe Upload API](https://wiki.aiursoft.com/ReadDoc/Integrated%20Website/Files.md#UploadFile)

Possible response:

```json
{
	"siteName": "anduin site",
	"filePath": "fuckyou/beijing.png",
	"internetPath": "https://probe.aiursoft.com/Download/Open/anduin%20site/fuckyou/beijing.png",
	"code": 0,
	"message": "Successfully uploaded your file."
}
```

The `filePath` is what you want.

### PR DESCRIPTION
**Pull request by xxyzz**
resolve #679

### CODE REVIEW

**Comment by Anduin2017** [comment]
Nexus has been changed and will return the file size when you calling the upload file API. So please make sure the display the current file size.

Please referenced here: https://wiki.aiursoft.com/ReadDoc/Integrated%20Website/Files.md#UploadFile

**Comment by xxyzz** [comment]
As long as the returned parameter is `fileSize`, we don't need to change the client code.

**Comment by Anduin2017** [comment]
So can you get the file size locally?

**Comment by xxyzz** [comment]
Why?

**Comment by Anduin2017** [comment]
For uploading files you need to display the file size. How did you get the file size without getting server response?

**Comment by xxyzz** [comment]
The upload api will tell the file size.....................................................

**Comment by Anduin2017** [comment]
I have just added the file size 30 seconds ago.

https://github.com/AiursoftWeb/Nexus/commit/401b42598f29834e64d06df4bc073971b8e087fe

**Comment by Anduin2017** [comment]
And if you upload a new file, it displays like this.

I guess you did not successfully implemented the file size.

**Comment by Anduin2017** [comment]
Please referenced here: 


https://wiki.aiursoft.com/ReadDoc/Integrated%20Website/Files.md#UploadFile

**Review by Anduin2017 — CHANGES_REQUESTED** [review]
Display correct file size.

**Comment by xxyzz** [comment]
Screen Shot 2019-09-21 at 17 33 12
`fileSize` not `size`.....

**Review by Anduin2017 — APPROVED** [review]

**Pull request merged**
