### PR TITLE
change: password valid method

### PR DESCRIPTION
**Pull request by zcharym**
change valid method into a regular expression, in case for future validation improvement.

### CODE REVIEW

**Review by Anduin2017 — CHANGES_REQUESTED** [review]
Seems the old logic is the password must be at least 6 characters. But your modification may change it to 8 characters.

**Review by Anduin2017 — APPROVED** [review]

**Comment by zcharym** [comment]
Oops.

**Comment by Anduin2017** [comment]
Thanks for your contribution! Once the automatic check is passed and we will merge this to our development branch! Thanks! 👍

**Comment by Anduin2017** [comment]
Your code does not satisfy our lint requirements. Please try to execute the following command to check your code issue:

```bash
$ npm run lint
```

Or:

```bash
$ ng lint --type-check && tsc
```

**Pull request merged**
