### PR TITLE
fix#436

### LINKED ISSUE #436: The user will become a ghost after leaving a group.
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `all`
- Last git commit: `a3351d0`
- Platform: `any`
- Browser: `chrome`

## How to repro

- Step 1: Create a new group and leave the talking page opened.
- Step 2: Open a new web browser and then use another account to join the group just created.
- Step 3: Send some messages in the second user.
- Step 4: Leave the group.
- Step 5: Back to the first user, **clear the browser cache in F12** and then refresh the page.
- Step 6: You can see the avatar of the second user is always loading and the nickname of it is always `New User`.

## Expected situation

I expect that the message should be deleted or display the correct sender.

## Other information

Nothing.

### PR DESCRIPTION
**Pull request by hv0905**
fix#436 with the new api

### CODE REVIEW

**Review by Anduin2017 — APPROVED** [review]

**Comment by Anduin2017** [comment]
Are you sure that you have deleted all code that is useless and for that old design? @hv0905

**Comment by Anduin2017** [comment]
If you also approve this, please merge it. @xxyzz But do not merge this before @xxyzz 's review. @hv0905

**Comment by Anduin2017** [comment]
@hv0905 Nicely done! The code is much more readable now!

**Comment by hv0905** [comment]
I might simplify the code tomorrow, don't merge it now pls

**Review by Xiangrui2019 — APPROVED** [review]

**Comment by hv0905** [comment]
...

**Pull request merged**
